language: node_js
node_js:
  - "12.2.0"

addons: 
chrome: stable

dist: trusty
sudo: required

script: echo "Running tests against $(node -v) ..."
cache: 
    - npm

branches: 
 only:
    - master

before_install: echo "Before Dependancy Install By Suraj..."

before_script: 
    # - npm install -g @angular/cli
    # - npm install -g firebase-tools

script: 
  # - npm install
  # - ng build --prod --base-href https://iamsurajdc.github.io/Grocery-Application/
  # - ng build --prod

# after_success: 
#   - firebase deploy --token $FIREBASE_TOKEN

# Deploy To Github Pages
deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true